### ISSUE TITLE
Let’s do the app from scratch :)

### ISSUE THREAD

**Issue by gr2m** [Rookies-RGSOC2016/Hoodie-electron-demo#19]
I’ve looked at the current state of the app and I think you two learned so much in the past weeks, probably the best thing to do would be to redo the app from scratch. I’d also remove everything that is not necessary at this point, like for example the sidebar and the top navbar

I’ve made a short screencast to explain my suggestions, these are of course only suggestions, open for discussion: 

https://dl.dropboxusercontent.com/u/732913/tmp/hoodie-electron-app-simplications-suggestions.mov

Once we only have one HTML file in which we show / hide different parts (list of applications / add new app form / show app page / edit app page), it will be much simpler to maintain. 

I think you can take the learnings from https://github.com/gr2m/localstorage-tutorial/ as well to create an `Applications` API (similar to `contactsStore` from the tutorial) with which we can add / find / update / delete applications.

Let me know if you have any questions, and if you like let’s have a call tomorrow around 4:30pm your time

**Comment by albacoretuna** [comment]
Sounds very good, and close to what we were talking about with @titayye in our face to face meeting on Friday. 
So to my understanding the app should have a "Create new project" button, that creates a new hoodie project by running the commands in get started docs of hoodie

right?

**Comment by gr2m** [comment]
The commands would be the ones listed here: https://github.com/hoodiehq/hoodie#setup

In detail:
1. Create a new folder based on the name.
   By default we could take the current users’s home directory + 'hoodie' + the app name, so if I enter something like "My Todo App", the path would be something like `/Users/gregor/hoodie/my-todo-app`. To dasherize the names we can use https://www.npmjs.com/package/to-id
2. Create `package.json`
   `json
   {
    "name": "my-todo-app",
    "version": "1.0.0",
    "scripts": {
      "start": "hoodie"
    }
   }
   `
   `my-todo-app` would be set to the folder name
3. Install hoodie with `npm install --save hoodie`. This will add `"hoodie"` to the package.json, too.

Now we can start the apps by running `npm start` in the folders.

One thing to consider is that if we want to run multiple Hoodie apps at once, they have to run on different ports. The default port number can be configured in a `.hoodierc` file, like so

``` ini
port=1234
```

As the Hoodie Desktop app should be aware of the Hoodie apps that it manages, we can go through and see what the next available port number is, and either write it into the `.hoodierc` file.

Hope this is not too confusing, we can go there step by step, just wanted to give you an overview :)

**Comment by flyjwayur** [comment]
@gr2m Thank you so much for the kind instruction and suggestions :) I got what we can do for the next step. I have a few questions. 
The first question is about 'show and hide'. Does it mean 'each one of elements or features(like create app, existing app etc) will be only displayed when it's needed, and when it's not needed, it'll be hidden from a user in the index.html page? :D
The second question is about the implementation of 'show and hide'. When I searched, it can be implemented in JS and CSS. Maybe in our app, we can use JS?

**Comment by flyjwayur** [comment]
This is a summary from the video :D
Step1> clean up html, css, js (remove what we don't need, we will add, when we need later)
1.What we need
1)welcome page 
2.existing apps
-folder where the static assets are
-link to open the app
-link to open the admin
-possibilities to change the app name and the folder
-only show the open the app and the admin when the app is running(start, not when it stops)
3. create new app
4. which app is currently running, which app is not 
5. focusing on displaying new app and existing apps above each other
(responsive design later)
-li needs to be inside of ul(not div)
-separate buttons : instead of btn-primary => btn(default one)
-something like separator
2. What we don't need now (no side bar, no menu, no nav)

Step2> Show the form and hide everything else
ex) hide new app button and existing apps
For editing, do it all in the index.html(not in the separate page).

**Comment by gr2m** [comment]
> The first question is about 'show and hide'. Does it mean 'each one of elements or features(like create app, existing app etc) will be only displayed when it's needed, and when it's not needed, it'll be hidden from a user in the index.html page? :D

Yes 

> The second question is about the implementation of 'show and hide'. When I searched, it can be implemented in JS and CSS. Maybe in our app, we can use JS?

Usually it’s a combination of both. You can show / hide with JavaScript alone, for example with jQuery, it’s simply `$('#mydiv').show()` and `$('#mydiv').hide()`. But I think it’s usually better to add CSS classes or data-attributes which you can then use in the CSS to show / hide elements

**Comment by gr2m** [comment]
done 👍
