### ISSUE TITLE
Setup ssh keys for GitHub

### ISSUE THREAD

**Issue by gr2m** [Rookies-RGSOC2016/Hoodie-electron-demo#3]
@titayye @flyjwayur I think you both currently use the `https://github.com/...` urls when you git clone projects to your terminal, not the `git@github.com:...` ones, correct? There is no problem with that, it’s only inconvenient because it is asking for your username & password all the time.

You can work around it by setting up ssh keys and adding them to your GitHub account. You can find instructions here: https://help.github.com/articles/generating-an-ssh-key/

Let me know if you have any questions :)

**Comment by flyjwayur** [comment]
@gr2m Thank you, Gregor. I set up the ssh-key. It's very useful and interesting. Without username & password, Github authenticated me automatically, when I pushed the code to Github :D I merged the READ.me file which had a pull-request, before I pushed it. It's fun to learn something new everyday!!

**Comment by gr2m** [comment]
@flyjwayur glad it works for you?

@titayye could you set it up as well? Let me know if you have any questions :)

**Comment by flyjwayur** [comment]
@gr2m Yes! :D It works for me. It's really convenient :)
