### ISSUE TITLE
Create start app API

### ISSUE THREAD

**Issue by flyjwayur** [Rookies-RGSOC2016/Hoodie-electron-demo#41]

**Comment by gr2m** [comment]
here is what I would suggest to do.
1. Change the `applist.update` method to also store a `state` property which can be `'started'` or `'stopped'`
2. Change the `applist.add` method to set `state` to `'stopped'` by default
3. use `applist.update` within the `applist.start` and `applist.stop` methods, changing the `state` property to `'started'` / `'stopped'` respectively 

makes sense?

**Comment by gr2m** [comment]
that’s done 👍
