### ISSUE TITLE
empty the previous input value in app name and rename app

### ISSUE THREAD

**Issue by flyjwayur** [Rookies-RGSOC2016/Hoodie-electron-demo#48]

**Comment by flyjwayur** [comment]
When we reload the page, the app name which has an id 'empty-text' is emtpy. But when we go back to the apps container page with clicking a button which id is #go-back-btn, the previous input is still in the app name input field. I'm trying the empty the value with '  $("#empty-text").empty()'.

**Comment by titay2** [comment]
$('#empty-text').val('') try this @flyjwayur its working fine for me :)

**Comment by flyjwayur** [comment]
@titay2 Titay :) Thanks a lot. Luckily, I also just figure that out too with console log as below :)
I wonder why empty() can't empty the value :) 

``` js
  //emtpy the previous input value
  console.log("empty()"+$("#empty-text").empty())
  $("#empty-text").empty()
  console.log("empty-text,val() after empty()"+$("#empty-text").val())

  console.log("empty-text,val('')"+$("#empty-text").val(""))
  $("#empty-text").val("")
  console.log("val() after val('')"+$("#empty-text").val())
```

**Comment by gr2m** [comment]
that’s working perfectly now 👍
