### ISSUE TITLE
Warp the project with Electron Framework  

### ISSUE THREAD

**Issue by flyjwayur** [Rookies-RGSOC2016/Hoodie-electron-demo#57]

**Comment by flyjwayur** [comment]
@gr2m @titay2 In package.json, there is this command line as below.

``` js
  "scripts": {
    "start": "electron ."
  },
```

But 'when I typed 'electron .' and 'npm start', those command lines were not working and the error message in the console, it's 'missing script start'. I'm trying to figure out how to put 'npm start'. But it can be a wrong guess to solve the problem.

**Comment by gr2m** [comment]
It worked for me :) Let's debug your setup in the standup today

**Comment by flyjwayur** [comment]
closed #59
